# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/anton/iphone/src/itorrent

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/anton/iphone/src/itorrent

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anton/iphone/src/itorrent/CMakeFiles /home/anton/iphone/src/itorrent/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/anton/iphone/src/itorrent/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named iTorrent

# Build rule for target.
iTorrent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iTorrent
.PHONY : iTorrent

# fast build rule for target.
iTorrent/fast:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/build
.PHONY : iTorrent/fast

Main.obj: Main.cpp.obj
.PHONY : Main.obj

# target to build an object file
Main.cpp.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/Main.cpp.obj
.PHONY : Main.cpp.obj

Main.i: Main.cpp.i
.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s
.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/Main.cpp.s
.PHONY : Main.cpp.s

Torrent.obj: Torrent.cpp.obj
.PHONY : Torrent.obj

# target to build an object file
Torrent.cpp.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/Torrent.cpp.obj
.PHONY : Torrent.cpp.obj

Torrent.i: Torrent.cpp.i
.PHONY : Torrent.i

# target to preprocess a source file
Torrent.cpp.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/Torrent.cpp.i
.PHONY : Torrent.cpp.i

Torrent.s: Torrent.cpp.s
.PHONY : Torrent.s

# target to generate assembly for a file
Torrent.cpp.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/Torrent.cpp.s
.PHONY : Torrent.cpp.s

benc.obj: benc.c.obj
.PHONY : benc.obj

# target to build an object file
benc.c.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/benc.c.obj
.PHONY : benc.c.obj

benc.i: benc.c.i
.PHONY : benc.i

# target to preprocess a source file
benc.c.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/benc.c.i
.PHONY : benc.c.i

benc.s: benc.c.s
.PHONY : benc.s

# target to generate assembly for a file
benc.c.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/benc.c.s
.PHONY : benc.c.s

bitset.obj: bitset.c.obj
.PHONY : bitset.obj

# target to build an object file
bitset.c.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/bitset.c.obj
.PHONY : bitset.c.obj

bitset.i: bitset.c.i
.PHONY : bitset.i

# target to preprocess a source file
bitset.c.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/bitset.c.i
.PHONY : bitset.c.i

bitset.s: bitset.c.s
.PHONY : bitset.s

# target to generate assembly for a file
bitset.c.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/bitset.c.s
.PHONY : bitset.c.s

bterror.obj: bterror.c.obj
.PHONY : bterror.obj

# target to build an object file
bterror.c.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/bterror.c.obj
.PHONY : bterror.c.obj

bterror.i: bterror.c.i
.PHONY : bterror.i

# target to preprocess a source file
bterror.c.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/bterror.c.i
.PHONY : bterror.c.i

bterror.s: bterror.c.s
.PHONY : bterror.s

# target to generate assembly for a file
bterror.c.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/bterror.c.s
.PHONY : bterror.c.s

bts.obj: bts.c.obj
.PHONY : bts.obj

# target to build an object file
bts.c.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/bts.c.obj
.PHONY : bts.c.obj

bts.i: bts.c.i
.PHONY : bts.i

# target to preprocess a source file
bts.c.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/bts.c.i
.PHONY : bts.c.i

bts.s: bts.c.s
.PHONY : bts.s

# target to generate assembly for a file
bts.c.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/bts.c.s
.PHONY : bts.c.s

context.obj: context.c.obj
.PHONY : context.obj

# target to build an object file
context.c.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/context.c.obj
.PHONY : context.c.obj

context.i: context.c.i
.PHONY : context.i

# target to preprocess a source file
context.c.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/context.c.i
.PHONY : context.c.i

context.s: context.c.s
.PHONY : context.s

# target to generate assembly for a file
context.c.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/context.c.s
.PHONY : context.c.s

gui/BrowserViewController.obj: gui/BrowserViewController.mm.obj
.PHONY : gui/BrowserViewController.obj

# target to build an object file
gui/BrowserViewController.mm.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/gui/BrowserViewController.mm.obj
.PHONY : gui/BrowserViewController.mm.obj

gui/BrowserViewController.i: gui/BrowserViewController.mm.i
.PHONY : gui/BrowserViewController.i

# target to preprocess a source file
gui/BrowserViewController.mm.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/gui/BrowserViewController.mm.i
.PHONY : gui/BrowserViewController.mm.i

gui/BrowserViewController.s: gui/BrowserViewController.mm.s
.PHONY : gui/BrowserViewController.s

# target to generate assembly for a file
gui/BrowserViewController.mm.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/gui/BrowserViewController.mm.s
.PHONY : gui/BrowserViewController.mm.s

gui/CrashReportSender.obj: gui/CrashReportSender.m.obj
.PHONY : gui/CrashReportSender.obj

# target to build an object file
gui/CrashReportSender.m.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/gui/CrashReportSender.m.obj
.PHONY : gui/CrashReportSender.m.obj

gui/CrashReportSender.i: gui/CrashReportSender.m.i
.PHONY : gui/CrashReportSender.i

# target to preprocess a source file
gui/CrashReportSender.m.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/gui/CrashReportSender.m.i
.PHONY : gui/CrashReportSender.m.i

gui/CrashReportSender.s: gui/CrashReportSender.m.s
.PHONY : gui/CrashReportSender.s

# target to generate assembly for a file
gui/CrashReportSender.m.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/gui/CrashReportSender.m.s
.PHONY : gui/CrashReportSender.m.s

gui/FSItem.obj: gui/FSItem.m.obj
.PHONY : gui/FSItem.obj

# target to build an object file
gui/FSItem.m.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/gui/FSItem.m.obj
.PHONY : gui/FSItem.m.obj

gui/FSItem.i: gui/FSItem.m.i
.PHONY : gui/FSItem.i

# target to preprocess a source file
gui/FSItem.m.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/gui/FSItem.m.i
.PHONY : gui/FSItem.m.i

gui/FSItem.s: gui/FSItem.m.s
.PHONY : gui/FSItem.s

# target to generate assembly for a file
gui/FSItem.m.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/gui/FSItem.m.s
.PHONY : gui/FSItem.m.s

gui/FilesViewController.obj: gui/FilesViewController.mm.obj
.PHONY : gui/FilesViewController.obj

# target to build an object file
gui/FilesViewController.mm.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/gui/FilesViewController.mm.obj
.PHONY : gui/FilesViewController.mm.obj

gui/FilesViewController.i: gui/FilesViewController.mm.i
.PHONY : gui/FilesViewController.i

# target to preprocess a source file
gui/FilesViewController.mm.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/gui/FilesViewController.mm.i
.PHONY : gui/FilesViewController.mm.i

gui/FilesViewController.s: gui/FilesViewController.mm.s
.PHONY : gui/FilesViewController.s

# target to generate assembly for a file
gui/FilesViewController.mm.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/gui/FilesViewController.mm.s
.PHONY : gui/FilesViewController.mm.s

gui/PluginView.obj: gui/PluginView.mm.obj
.PHONY : gui/PluginView.obj

# target to build an object file
gui/PluginView.mm.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/gui/PluginView.mm.obj
.PHONY : gui/PluginView.mm.obj

gui/PluginView.i: gui/PluginView.mm.i
.PHONY : gui/PluginView.i

# target to preprocess a source file
gui/PluginView.mm.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/gui/PluginView.mm.i
.PHONY : gui/PluginView.mm.i

gui/PluginView.s: gui/PluginView.mm.s
.PHONY : gui/PluginView.s

# target to generate assembly for a file
gui/PluginView.mm.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/gui/PluginView.mm.s
.PHONY : gui/PluginView.mm.s

gui/RegisterViewController.obj: gui/RegisterViewController.mm.obj
.PHONY : gui/RegisterViewController.obj

# target to build an object file
gui/RegisterViewController.mm.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/gui/RegisterViewController.mm.obj
.PHONY : gui/RegisterViewController.mm.obj

gui/RegisterViewController.i: gui/RegisterViewController.mm.i
.PHONY : gui/RegisterViewController.i

# target to preprocess a source file
gui/RegisterViewController.mm.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/gui/RegisterViewController.mm.i
.PHONY : gui/RegisterViewController.mm.i

gui/RegisterViewController.s: gui/RegisterViewController.mm.s
.PHONY : gui/RegisterViewController.s

# target to generate assembly for a file
gui/RegisterViewController.mm.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/gui/RegisterViewController.mm.s
.PHONY : gui/RegisterViewController.mm.s

gui/TrackersViewController.obj: gui/TrackersViewController.mm.obj
.PHONY : gui/TrackersViewController.obj

# target to build an object file
gui/TrackersViewController.mm.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/gui/TrackersViewController.mm.obj
.PHONY : gui/TrackersViewController.mm.obj

gui/TrackersViewController.i: gui/TrackersViewController.mm.i
.PHONY : gui/TrackersViewController.i

# target to preprocess a source file
gui/TrackersViewController.mm.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/gui/TrackersViewController.mm.i
.PHONY : gui/TrackersViewController.mm.i

gui/TrackersViewController.s: gui/TrackersViewController.mm.s
.PHONY : gui/TrackersViewController.s

# target to generate assembly for a file
gui/TrackersViewController.mm.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/gui/TrackersViewController.mm.s
.PHONY : gui/TrackersViewController.mm.s

httpget.obj: httpget.m.obj
.PHONY : httpget.obj

# target to build an object file
httpget.m.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/httpget.m.obj
.PHONY : httpget.m.obj

httpget.i: httpget.m.i
.PHONY : httpget.i

# target to preprocess a source file
httpget.m.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/httpget.m.i
.PHONY : httpget.m.i

httpget.s: httpget.m.s
.PHONY : httpget.s

# target to generate assembly for a file
httpget.m.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/httpget.m.s
.PHONY : httpget.m.s

peer.obj: peer.c.obj
.PHONY : peer.obj

# target to build an object file
peer.c.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/peer.c.obj
.PHONY : peer.c.obj

peer.i: peer.c.i
.PHONY : peer.i

# target to preprocess a source file
peer.c.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/peer.c.i
.PHONY : peer.c.i

peer.s: peer.c.s
.PHONY : peer.s

# target to generate assembly for a file
peer.c.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/peer.c.s
.PHONY : peer.c.s

peerexchange.obj: peerexchange.c.obj
.PHONY : peerexchange.obj

# target to build an object file
peerexchange.c.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/peerexchange.c.obj
.PHONY : peerexchange.c.obj

peerexchange.i: peerexchange.c.i
.PHONY : peerexchange.i

# target to preprocess a source file
peerexchange.c.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/peerexchange.c.i
.PHONY : peerexchange.c.i

peerexchange.s: peerexchange.c.s
.PHONY : peerexchange.s

# target to generate assembly for a file
peerexchange.c.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/peerexchange.c.s
.PHONY : peerexchange.c.s

random.obj: random.c.obj
.PHONY : random.obj

# target to build an object file
random.c.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/random.c.obj
.PHONY : random.c.obj

random.i: random.c.i
.PHONY : random.i

# target to preprocess a source file
random.c.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/random.c.i
.PHONY : random.c.i

random.s: random.c.s
.PHONY : random.s

# target to generate assembly for a file
random.c.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/random.c.s
.PHONY : random.c.s

segmenter.obj: segmenter.c.obj
.PHONY : segmenter.obj

# target to build an object file
segmenter.c.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/segmenter.c.obj
.PHONY : segmenter.c.obj

segmenter.i: segmenter.c.i
.PHONY : segmenter.i

# target to preprocess a source file
segmenter.c.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/segmenter.c.i
.PHONY : segmenter.c.i

segmenter.s: segmenter.c.s
.PHONY : segmenter.s

# target to generate assembly for a file
segmenter.c.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/segmenter.c.s
.PHONY : segmenter.c.s

sha1.obj: sha1.c.obj
.PHONY : sha1.obj

# target to build an object file
sha1.c.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/sha1.c.obj
.PHONY : sha1.c.obj

sha1.i: sha1.c.i
.PHONY : sha1.i

# target to preprocess a source file
sha1.c.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/sha1.c.i
.PHONY : sha1.c.i

sha1.s: sha1.c.s
.PHONY : sha1.s

# target to generate assembly for a file
sha1.c.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/sha1.c.s
.PHONY : sha1.c.s

strbuf.obj: strbuf.c.obj
.PHONY : strbuf.obj

# target to build an object file
strbuf.c.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/strbuf.c.obj
.PHONY : strbuf.c.obj

strbuf.i: strbuf.c.i
.PHONY : strbuf.i

# target to preprocess a source file
strbuf.c.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/strbuf.c.i
.PHONY : strbuf.c.i

strbuf.s: strbuf.c.s
.PHONY : strbuf.s

# target to generate assembly for a file
strbuf.c.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/strbuf.c.s
.PHONY : strbuf.c.s

stream.obj: stream.c.obj
.PHONY : stream.obj

# target to build an object file
stream.c.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/stream.c.obj
.PHONY : stream.c.obj

stream.i: stream.c.i
.PHONY : stream.i

# target to preprocess a source file
stream.c.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/stream.c.i
.PHONY : stream.c.i

stream.s: stream.c.s
.PHONY : stream.s

# target to generate assembly for a file
stream.c.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/stream.c.s
.PHONY : stream.c.s

types.obj: types.c.obj
.PHONY : types.obj

# target to build an object file
types.c.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/types.c.obj
.PHONY : types.c.obj

types.i: types.c.i
.PHONY : types.i

# target to preprocess a source file
types.c.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/types.c.i
.PHONY : types.c.i

types.s: types.c.s
.PHONY : types.s

# target to generate assembly for a file
types.c.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/types.c.s
.PHONY : types.c.s

udpproto.obj: udpproto.c.obj
.PHONY : udpproto.obj

# target to build an object file
udpproto.c.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/udpproto.c.obj
.PHONY : udpproto.c.obj

udpproto.i: udpproto.c.i
.PHONY : udpproto.i

# target to preprocess a source file
udpproto.c.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/udpproto.c.i
.PHONY : udpproto.c.i

udpproto.s: udpproto.c.s
.PHONY : udpproto.s

# target to generate assembly for a file
udpproto.c.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/udpproto.c.s
.PHONY : udpproto.c.s

util.obj: util.cpp.obj
.PHONY : util.obj

# target to build an object file
util.cpp.obj:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/util.cpp.obj
.PHONY : util.cpp.obj

util.i: util.cpp.i
.PHONY : util.i

# target to preprocess a source file
util.cpp.i:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/util.cpp.i
.PHONY : util.cpp.i

util.s: util.cpp.s
.PHONY : util.s

# target to generate assembly for a file
util.cpp.s:
	$(MAKE) -f CMakeFiles/iTorrent.dir/build.make CMakeFiles/iTorrent.dir/util.cpp.s
.PHONY : util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... iTorrent"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Main.obj"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... Torrent.obj"
	@echo "... Torrent.i"
	@echo "... Torrent.s"
	@echo "... benc.obj"
	@echo "... benc.i"
	@echo "... benc.s"
	@echo "... bitset.obj"
	@echo "... bitset.i"
	@echo "... bitset.s"
	@echo "... bterror.obj"
	@echo "... bterror.i"
	@echo "... bterror.s"
	@echo "... bts.obj"
	@echo "... bts.i"
	@echo "... bts.s"
	@echo "... context.obj"
	@echo "... context.i"
	@echo "... context.s"
	@echo "... gui/BrowserViewController.obj"
	@echo "... gui/BrowserViewController.i"
	@echo "... gui/BrowserViewController.s"
	@echo "... gui/CrashReportSender.obj"
	@echo "... gui/CrashReportSender.i"
	@echo "... gui/CrashReportSender.s"
	@echo "... gui/FSItem.obj"
	@echo "... gui/FSItem.i"
	@echo "... gui/FSItem.s"
	@echo "... gui/FilesViewController.obj"
	@echo "... gui/FilesViewController.i"
	@echo "... gui/FilesViewController.s"
	@echo "... gui/PluginView.obj"
	@echo "... gui/PluginView.i"
	@echo "... gui/PluginView.s"
	@echo "... gui/RegisterViewController.obj"
	@echo "... gui/RegisterViewController.i"
	@echo "... gui/RegisterViewController.s"
	@echo "... gui/TrackersViewController.obj"
	@echo "... gui/TrackersViewController.i"
	@echo "... gui/TrackersViewController.s"
	@echo "... httpget.obj"
	@echo "... httpget.i"
	@echo "... httpget.s"
	@echo "... peer.obj"
	@echo "... peer.i"
	@echo "... peer.s"
	@echo "... peerexchange.obj"
	@echo "... peerexchange.i"
	@echo "... peerexchange.s"
	@echo "... random.obj"
	@echo "... random.i"
	@echo "... random.s"
	@echo "... segmenter.obj"
	@echo "... segmenter.i"
	@echo "... segmenter.s"
	@echo "... sha1.obj"
	@echo "... sha1.i"
	@echo "... sha1.s"
	@echo "... strbuf.obj"
	@echo "... strbuf.i"
	@echo "... strbuf.s"
	@echo "... stream.obj"
	@echo "... stream.i"
	@echo "... stream.s"
	@echo "... types.obj"
	@echo "... types.i"
	@echo "... types.s"
	@echo "... udpproto.obj"
	@echo "... udpproto.i"
	@echo "... udpproto.s"
	@echo "... util.obj"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

